import datetime
from typing import Optional
from lar.node import BaseNode
from lar.state import GraphState

try:
    from lar import __version__ as _LAR_VERSION
except Exception:  # pragma: no cover - version import is best-effort
    _LAR_VERSION = "unknown"


class SyntheticMarkerNode(BaseNode):
    """
    Marks AI-generated content per the Art. 50 transparency regime.

    Two distinct obligations, selected by ``marker_type``:

    * ``METADATA`` → **Art. 50(2)** — providers of AI systems generating synthetic
      audio/image/video/text must mark outputs in a **machine-readable** format,
      detectable as artificially generated (effective, interoperable, robust "as
      far as technically feasible").  This path writes a simulated C2PA manifest.
    * ``VISIBLE``  → **Art. 50(1)** (AI-interaction disclosure to natural persons)
      and **Art. 50(4)** (deep fakes / AI-generated text published to inform the
      public on matters of public interest) — a human-readable disclosure.  This
      path appends a plain-language disclaimer.

    A production deployment usually needs BOTH: run one node with ``METADATA`` and
    one with ``VISIBLE``.

    Timeline note: Art. 50 applies from 2 August 2026 and was **not** amended by
    the Digital Omnibus (Regulation (EU) 2026/1744).  Providers of generative AI
    systems already on the market have until **2 December 2026** to implement the
    Art. 50(2) machine-readable marking duty.
    """

    EU_REFERENCE_METADATA = (
        "Art. 50(2) EU AI Act — machine-readable marking of synthetic content "
        "(providers of generative AI systems)"
    )
    EU_REFERENCE_VISIBLE = (
        "Art. 50(1)/(4) EU AI Act — human-readable AI disclosure to affected "
        "natural persons / deep-fake & public-interest text labelling"
    )

    def __init__(self,
                 input_key: str,
                 output_key: Optional[str] = None,
                 marker_type: str = "VISIBLE",
                 next_node: Optional[BaseNode] = None):
        """
        Args:
            input_key: The state key containing the content to mark.
            output_key: The state key to save marked content (defaults to overwriting input_key).
            marker_type: "VISIBLE" (Art. 50(1)/(4) text disclaimer) or
                "METADATA" (Art. 50(2) machine-readable / simulated C2PA manifest).
        """
        self.input_key = input_key
        self.output_key = output_key or input_key
        self.marker_type = marker_type.upper()
        self.next_node = next_node

    @property
    def eu_reference(self) -> str:
        return (
            self.EU_REFERENCE_METADATA
            if self.marker_type == "METADATA"
            else self.EU_REFERENCE_VISIBLE
        )

    def execute(self, state: GraphState):
        content = state.get(self.input_key)
        if not content:
            return self.next_node

        timestamp = datetime.datetime.utcnow().isoformat()

        if self.marker_type == "VISIBLE":
            if isinstance(content, str):
                marked_content = (
                    f"{content}\n\n[Disclaimer: This content was generated by an AI "
                    f"system on {timestamp}. (EU AI Act Art. 50(1)/(4).)]"
                )
            else:
                # If it's a dict, add a disclaimer field
                marked_content = content.copy() if isinstance(content, dict) else {"original": content}
                marked_content["_ai_disclaimer"] = f"Generated by AI on {timestamp}"
                marked_content["_ai_disclaimer_basis"] = self.EU_REFERENCE_VISIBLE

        elif self.marker_type == "METADATA":
            # Simulate a C2PA metadata wrapper (Art. 50(2) machine-readable marking).
            # A production deployment substitutes a real C2PA / SynthID-class signer.
            marked_content = {
                "c2pa_manifest": {
                    "generator": f"Lár {_LAR_VERSION}",
                    "timestamp": timestamp,
                    "assertion": "AI_GENERATED",
                    "eu_reference": self.EU_REFERENCE_METADATA,
                    "note": "Simulated manifest — replace with a real C2PA signer in production.",
                },
                "content": content,
            }
        else:
            marked_content = content

        state.set("synthetic_marker_reference", self.eu_reference)
        print(
            f"  [SyntheticMarkerNode] Applied {self.marker_type} marking to "
            f"'{self.input_key}' ({self.eu_reference.split(' — ')[0]})."
        )
        state.set(self.output_key, marked_content)

        return self.next_node
